service:
  name: auction-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  profile: sunny
  stage: ${opt:stage , 'dev'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - !GetAtt AuctionTable.Arn
    - Effect: Allow
      Action:
        - iot:Publish
      Resource: '*'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  createAuction:
    handler: handler.createAuction
    events:
      - http:
          method: POST
          path: /createAuction
  getAuctions:
    handler: getAuctionHandler.getAuctions
    events:
      - http:
          method: GET
          path: /getAuctions
  getAuction:
    handler: getAuctionHandler.getAuction
    events:
      - http:
          method: GET
          path: /getAuction/{id}
  iotDevice:
    handler: iotHandler.iot
    events:
      - iot:
          name: myIoTEvent
          description: An IoT event
          sql: "SELECT * , topic(4) as topicName FROM 'sunny/iot/topic/#'"

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 'streamdatabucket'
        VersioningConfiguration:
          Status: Enabled
    AuctionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
